export const MATCHA_FLUID_CONFIG = {
  bowl: {
    centerUv: 0.5,
    collisionMarginRatio: 0.035,
    constraint: {
      frictionWallMultiplier: 0.42,
      inwardWallMultiplier: 0.52,
      tangentBaseRatio: 0.45,
      tangentWallMultiplier: 0.35,
    },
    minimumNormalizedRadius: 0.0001,
    radiusRatio: 0.48,
    wallDampingMultiplier: 0.58,
    wallFrictionStartRatio: 0.72,
  },
  canvasSizePixels: 640,
  collision: {
    minimumForce: 0.45,
    minimumSpeedUv: 0.0005,
    rippleForceMultiplier: 0.42,
    rippleForceMaximum: 1.2,
    rippleRadiusBasePixels: 140,
    rippleRadiusSpeedMultiplier: 16,
    rippleSpeedThresholdUv: 0.004,
    rippleStrengthThreshold: 0.75,
  },
  initialRipples: {
    count: 4,
    forceRange: [0.2, 0.6] as const,
    radiusPixelsRange: [150, 360] as const,
  },
  flowField: {
    diagonalX: {
      influence: 0.45,
      spatialFrequency: 10.7,
      timeBaseFrequency: 0.28,
      timeFlowMultiplier: 0.34,
    },
    diagonalY: {
      influence: 0.48,
      spatialFrequency: 7.7,
      timeBaseFrequency: 0.22,
      timeFlowMultiplier: 0.62,
    },
    displacement: {
      agitationEnergyMultiplier: 0.82,
      baseEnergy: 0.3,
      viscosityEnergyMultiplier: 0.42,
      xAmplitudeRatio: 0.13,
      yAmplitudeRatio: 0.11,
    },
    primaryX: {
      influence: 0.72,
      spatialFrequency: 8.2,
      timeBaseFrequency: 0.42,
      timeFlowMultiplier: 0.48,
    },
    primaryY: {
      influence: 0.66,
      spatialFrequency: 9.1,
      timeBaseFrequency: 0.36,
      timeFlowMultiplier: 0.44,
    },
  },
  limits: {
    ripples: 28,
    stirs: 34,
  },
  renderer: {
    foamDust: {
      alphaBaseRatio: 0.65,
      alphaOscillationRatio: 0.35,
      colorRgb: [242, 250, 178] as const,
      timeSeedMultiplier: 0.02,
      xDeformationRatio: 0.08,
      yDeformationRatio: 0.06,
    },
    mesh: {
      maximumStretchRatio: 0.055,
      stretchDisplacementMultiplier: 0.0022,
    },
  },
  ripple: {
    bandRadiusRatio: 0.36,
    defaultForce: 1,
    defaultRadiusPixels: 240,
    distanceEpsilonPixels: 0.001,
    lifetimeSeconds: 2.2,
    lifeExponent: 2,
    magnitudeRatio: 0.12,
    ringDecayRadiusRatio: 0.19,
    seedRange: 1000,
    spatialFrequency: 0.085,
    timeFrequency: 12.5,
    waveFrontSpeedRatio: 0.72,
  },
  simulation: {
    agitation: 1.8,
    deformationPixels: 36,
    deltaSeconds: {
      maximum: 0.045,
      minimum: 0.001,
    },
    flowSpeed: 2,
    meshCellPixels: 4,
    viscosity: 1,
  },
  stir: {
    distanceEpsilonPixels: 0.001,
    falloffExponent: 2,
    lifetimeSeconds: 1.25,
    pushDistanceOffsetPixels: 1,
    radiusAgitationMultiplierPixels: 120,
    radiusBasePixels: 135,
    swirlInfluence: 0.038,
    velocityInfluence: 0.13,
    wallFrictionMultiplier: 0.36,
  },
  texture: {
    baseColor: "#8eaa2e",
    foamDust: {
      alphaRange: [0.03, 0.13] as const,
      areaPerParticlePixels: 24000,
      radiusPixelsRange: [0.35, 1.35] as const,
      seedRange: 1000,
    },
    meshPaddingPixels: 2,
  },
} as const;
